window.MARE_LENTO_CONFIG = Object.freeze({
  SUPABASE_URL: "https://hrudftrkqzhjyvgoyurb.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_hBPyP_xFyxMHEfK0ogCC6Q_lTCbJhFJ",
  WHATSAPP_NUMBER: "48880313233",
  CONTACT_EMAIL: "marelento.booking@gmail.com",
  TURNSTILE_SITE_KEY: "",
  PRICING: Object.freeze({
    currency: "EUR",
    includedGuests: 2,
    extraGuestNightly: 10,
    cleaningFee: 45,
    weekendMultiplier: 1.08,
    weeklyDiscount: 0.05,
    longStayDiscount: 0.1,
    seasonalAnchors: Object.freeze([
      { month: 1, day: 15, rate: 62 },
      { month: 2, day: 15, rate: 62 },
      { month: 3, day: 15, rate: 68 },
      { month: 4, day: 15, rate: 76 },
      { month: 5, day: 15, rate: 86 },
      { month: 6, day: 15, rate: 105 },
      { month: 7, day: 15, rate: 128 },
      { month: 8, day: 15, rate: 145 },
      { month: 9, day: 15, rate: 105 },
      { month: 10, day: 15, rate: 78 },
      { month: 11, day: 15, rate: 64 },
      { month: 12, day: 15, rate: 68 },
    ]),
  }),
});
